// <auto-generated />
namespace HoangAn1611061946.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class KhoiTaoModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KhoiTaoModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201903280225374_KhoiTaoModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
